# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PCPreproject
                                 A QGIS plugin
 This plugin transform vector oblects into perspective cylindrical projections
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-04-06
        copyright            : (C) 2021 by MSU
        email                : grita005@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PCPreproject class from file PCPreproject.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pcp_reproject import PCPreproject
    return PCPreproject(iface)
